---
- name: Install build deps with virtual flag
  become: yes
  become_method: sudo
  shell: apk add --virtual build-deps

- name: Installing base packages
  apk:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-base 
    - cmake 
    - go 
    - llvm 
    - perl 
    - python-dev
    - libxt 
    - libx11 
    - libstdc++
    - go
  become: yes
  become_method: sudo

- name: vimrc for GO
  copy: src=go.vim dest="/home/{{ os.user }}/.vim/ftplugin/go.vim" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
  when:
    - languages
    - languages.go

- name: vim plugins for GO
  become: no
  git: 
    repo: "https://github.com/{{ item }}.git"
    dest: "/home/{{ os.user }}/.vim/pack/plugins/start/{{ item|replace('/', '_') }}"
  with_items:
    - 'fatih/vim-go'
    - 'Shougo/neocomplete.vim'
  when:
    - languages
    - languages.go
- name: Configure YouCompleteMe
  become: no
  shell: |
    ./install.py --go-completer
    chdir=/home/{{ os.user }}/.vim/pack/plugins/start/YouCompleteMe

- name: Remove build deps
  become: yes
  become_method: sudo
  shell: apk del --virtual build-deps
