---
- name: Add Gopher Repository
  become: yes
  become_method: sudo
  shell: |
    add-apt-repository -y ppa:gophers/archive
- name: Installing base packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential 
    - cmake 
    - llvm 
    - perl 
    - python-dev
    - golang-1.9-go
  become: yes
  become_method: sudo
- name: Symlink Go 
  file:
    src: /usr/lib/go-1.9/bin/go
    dest: /usr/bin/go
    owner: "{{ os.user }}"
    group: "{{ os.user }}"
    state: link
  become: yes
  become_method: sudo
- name: vimrc for GO
  copy: src=go.vim dest="/home/{{ os.user }}/.vim/ftplugin/go.vim" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no

- name: vim plugins for GO
  become: no
  git: 
    repo: "https://github.com/{{ item }}.git"
    dest: "/home/{{ os.user }}/.vim/pack/plugins/start/{{ item|replace('/', '_') }}"
  with_items:
    - 'fatih/vim-go'
    - 'Shougo/neocomplete.vim'
- name: Configure YouCompleteMe
  become: no
  shell: |
    ./install.py --go-completer
    chdir=/home/{{ os.user }}/.vim/pack/plugins/start/YouCompleteMe
